// src/components/App.vue
<template>
  <div id="app">
    <!-- loading -->
    <div class="loading" v-if="loading">
      <h1>loading</h1>
    </div>
    <!-- success -->
    <div class="content" v-else>
      <h1>hello</h1>
    </div>
  </div>
</template>

<script>
export default {
  name: 'app',
  mounted() {
    navigator.geolocation.getCurrentPosition(
      async data => {
        const { latitude, longitude } = data.coords;
        const res = await axios.get("/api/tracks", {
          params: {
            latitude,
            longitude
          }
        });
        this.city = res.data.city_name;
        this.playlists = res.data.playlist.playlists.items
        this.loading = false
      },
      err => console.error(err)
    )
  },
  data: {
    loading: true,
    city: "読み込み中...",
    playlists: []
  },
  watch: {
    playlists() {
      console.log(this.playlists[0])
    }
  },
  methods: {
    logout() {
      document.cookie = "musi-token=; max-age=0";
      location.reload()
    }
  }
}
</script>

// src/components/App.tsx
import * as React from "react"
import axios from "axios";
import * as cookie from "js-cookie";

// components
import Head from "./Head";
import Foot from "./Foot";
import PlayList from "./PlayList";
import Loading from "./Loading";
import Map from "./Map";

interface State {
  loading: boolean;
  cityName: string;
  weather: string;
  playlists;
  latitude: number;
  longitude: number;
}

export default class App extends React.Component<any, State> {

  componentDidMount() {
    this.fetchTracks()
  }

  constructor(props) {
    super(props);

    this.state = {
      loading: true,
      cityName: "",
      weather: "",
      playlists: [],
      latitude: 59.95,
      longitude: 30.33
    }
  }

  render() {
    const comp = this.state.loading ? <Loading/> : (
      <>
        <PlayList weather={this.state.weather} cityName={this.state.cityName} playlists={this.state.playlists} />
        <Map lat={this.state.latitude} lng={this.state.longitude}/>
      </>
    );

    return (
      <>
        <Head/>
          {comp}
        <Foot/>
      </>
    )
  }

  fetchTracks = () => {
    navigator.geolocation.getCurrentPosition(
      async data => {
        const { latitude, longitude } = data.coords;
        const res = await axios.get("/api/tracks", {
          params: {
            latitude,
            longitude
          }
        });
        this.setState({
          loading: false,
          cityName: res.data.city_name,
          weather: res.data.weather,
          playlists: res.data.playlist.playlists.items || [],
          latitude,
          longitude
        })
      },
      err => console.error(err)
    )
  }

  logout() {
    cookie.remove("musi-token");
    location.reload();
  }

}
